/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.TicketingAgentRole;

import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 粥嘚嘚
 */
public class ManageTicketingJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private UserAccount userAccount; 
    public static List<Object[]> workRequestQueue = new ArrayList<>();

    /**
     * Creates new form ManageTicketingJPanel
     */
    public ManageTicketingJPanel(JPanel userProcessContainer, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        
       // tableData = new ArrayList<>();
        //tableData.add(new Object[]{"Concert A", "Organizer 1", "", "Pending", ""});
        //tableData.add(new Object[]{"Concert B", "Organizer 2", "", "Pending", ""});
        //tableData.add(new Object[]{"Concert C", "Organizer 3", "", "Pending", ""});

        populateTable();
        setupComponents();
    }
    
     private void setupComponents() {
        
        assignJButton1.addActionListener(evt -> assignJButton1ActionPerformed(evt));
        processJButton1.addActionListener(evt -> processJButton1ActionPerformed(evt));
        refreshJButton1.addActionListener(evt -> refreshJButton1ActionPerformed(evt));
    }
    
     
     public static void addWorkRequest(Object[] workRequest) {
        if (workRequest.length < 8) { // 检查数组长度是否小于 8
            Object[] fullRequest = new Object[8];
            System.arraycopy(workRequest, 0, fullRequest, 0, workRequest.length); // 扩展长度
            workRequestQueue.add(fullRequest);
        } else {
            workRequestQueue.add(workRequest); // 长度足够直接添加
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        workRequestJTable1 = new javax.swing.JTable();
        assignJButton1 = new javax.swing.JButton();
        processJButton1 = new javax.swing.JButton();
        refreshJButton1 = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        workRequestJTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Event Name", "Sender", "Receiver", "Status", "Remark", "Suggested Price", "Actual Price", "Category"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(workRequestJTable1);

        assignJButton1.setText("Assign to me");
        assignJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignJButton1ActionPerformed(evt);
            }
        });

        processJButton1.setText("Process");
        processJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processJButton1ActionPerformed(evt);
            }
        });

        refreshJButton1.setText("Refresh");
        refreshJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButton1ActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setText("Manage Performance");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(assignJButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(processJButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(refreshJButton1)
                .addGap(16, 16, 16))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addGap(248, 248, 248)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 864, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(refreshJButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assignJButton1)
                    .addComponent(processJButton1))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        add(jPanel1, "card6");
    }// </editor-fold>//GEN-END:initComponents

    private void assignJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignJButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = workRequestJTable1.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a request to assign.");
            return;
        }

         DefaultTableModel model = (DefaultTableModel) workRequestJTable1.getModel();
        Object[] row = workRequestQueue.get(selectedRow);


        if (row[2] != null && !row[2].toString().isEmpty()) { // 检查是否已被分配
            JOptionPane.showMessageDialog(null, "This request is already assigned.");
            return;
        }
        row[2] = "Assigned to me"; // Receiver列
        row[3] = "Pending";  
        
         JOptionPane.showMessageDialog(this, "Request assigned successfully!");
        
        populateTable();
    }//GEN-LAST:event_assignJButton1ActionPerformed

    private void processJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processJButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = workRequestJTable1.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a request to process.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) workRequestJTable1.getModel();
        Object[] row = workRequestQueue.get(selectedRow);
        String status = (String) row[3];
        
        
        if (!"Pending".equals(status)) {
            JOptionPane.showMessageDialog(null, "Only assigned requests can be processed.");
            return;
            }

        ProcessTicketCheckJPanel processPanel = new ProcessTicketCheckJPanel(userProcessContainer, selectedRow, workRequestQueue);
        userProcessContainer.add("ProcessTicketCheckJPanel", processPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_processJButton1ActionPerformed

    private void refreshJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButton1ActionPerformed
        // TODO add your handling code here:
          populateTable();
    }//GEN-LAST:event_refreshJButton1ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);
         CardLayout layout = (CardLayout) userProcessContainer.getLayout();
         layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed
    private void populateTable() {
            DefaultTableModel model = (DefaultTableModel) workRequestJTable1.getModel();
            model.setRowCount(0);
            
         for (Object[] row : workRequestQueue) {
             System.out.println("Populating row: " + java.util.Arrays.toString(row)); // 调试输出
            // 显示该用户相关的请求
            if (row[2] == null || row[2].equals(userAccount.getUsername())) {
                model.addRow(row);
            }
        }
    }
    
    public void refreshTable() {
    populateTable(); 
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignJButton1;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton processJButton1;
    private javax.swing.JButton refreshJButton1;
    private javax.swing.JTable workRequestJTable1;
    // End of variables declaration//GEN-END:variables
}
