/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.TicketingAgentRole;

import Business.UserAccount.UserAccount;
import Model.Event;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import ui.Organizer.EventManagementJPanel;

/**
 *
 * @author 粥嘚嘚
 */
public class ManageTicketingJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private UserAccount userAccount; 
    public static List<Object[]> workRequestQueue = new ArrayList<>();

    /**
     * Creates new form ManageTicketingJPanel
     */
    public ManageTicketingJPanel(JPanel userProcessContainer, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        
       // tableData = new ArrayList<>();
        //tableData.add(new Object[]{"Concert A", "Organizer 1", "", "Pending", ""});
        //tableData.add(new Object[]{"Concert B", "Organizer 2", "", "Pending", ""});
        //tableData.add(new Object[]{"Concert C", "Organizer 3", "", "Pending", ""});

        populateTable();
        setupComponents();
    }
    
     private void setupComponents() {
        
        assignJButton1.addActionListener(evt -> assignJButton1ActionPerformed(evt));
        processJButton1.addActionListener(evt -> processJButton1ActionPerformed(evt));
        refreshJButton1.addActionListener(evt -> refreshJButton1ActionPerformed(evt));
    }
    
     
     public static void addWorkRequest(Object[] workRequest) {
        if (workRequest.length < 8) { // 检查数组长度是否小于 8
            Object[] fullRequest = new Object[8];
            System.arraycopy(workRequest, 0, fullRequest, 0, workRequest.length); // 扩展长度
            workRequestQueue.add(fullRequest);
        } else {
            workRequestQueue.add(workRequest); // 长度足够直接添加
        }
         System.out.println("Added work request: " + java.util.Arrays.toString(workRequest));
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        workRequestJTable1 = new javax.swing.JTable();
        assignJButton1 = new javax.swing.JButton();
        processJButton1 = new javax.swing.JButton();
        refreshJButton1 = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnAddtoList = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        workRequestJTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Event Name", "Sender", "Receiver", "Status", "Remark", "Suggested Price", "Actual Price", "Category"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(workRequestJTable1);

        assignJButton1.setText("Assign to me");
        assignJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignJButton1ActionPerformed(evt);
            }
        });

        processJButton1.setText("Process");
        processJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processJButton1ActionPerformed(evt);
            }
        });

        refreshJButton1.setText("Refresh");
        refreshJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButton1ActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setText("Manage Performance");

        btnAddtoList.setText("Add to List");
        btnAddtoList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddtoListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(assignJButton1)
                .addGap(121, 121, 121)
                .addComponent(processJButton1)
                .addGap(139, 139, 139)
                .addComponent(btnAddtoList)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(refreshJButton1)
                .addGap(16, 16, 16))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addGap(248, 248, 248)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 864, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(refreshJButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assignJButton1)
                    .addComponent(processJButton1)
                    .addComponent(btnAddtoList))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        add(jPanel1, "card6");
    }// </editor-fold>//GEN-END:initComponents

    private void assignJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignJButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = workRequestJTable1.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a request to assign.");
            return;
        }

         DefaultTableModel model = (DefaultTableModel) workRequestJTable1.getModel();
        Object[] row = workRequestQueue.get(selectedRow);


        if (row[2] != null && !row[2].toString().isEmpty()) { // 检查是否已被分配
            JOptionPane.showMessageDialog(null, "This request is already assigned.");
            return;
        }
        row[2] = "Assigned to me"; // Receiver列
        row[3] = "Pending";  
        
         JOptionPane.showMessageDialog(this, "Request assigned successfully!");
        
        populateTable();
    }//GEN-LAST:event_assignJButton1ActionPerformed

    private void processJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processJButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = workRequestJTable1.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a request to process.");
            return;
        }

        //DefaultTableModel model = (DefaultTableModel) workRequestJTable1.getModel();
        Object[] row = workRequestQueue.get(selectedRow);
        String status = (String) row[3];
        
        
        if (!"Pending".equals(status)) {
            JOptionPane.showMessageDialog(null, "Only assigned requests can be processed.");
            return;
            }

        ProcessTicketCheckJPanel processPanel = new ProcessTicketCheckJPanel(userProcessContainer, selectedRow, workRequestQueue);
        userProcessContainer.add("ProcessTicketCheckJPanel", processPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_processJButton1ActionPerformed

    private void refreshJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButton1ActionPerformed
        // TODO add your handling code here:
          populateTable();
    }//GEN-LAST:event_refreshJButton1ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);
         CardLayout layout = (CardLayout) userProcessContainer.getLayout();
         layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddtoListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddtoListActionPerformed
        // TODO add your handling code here:
         int selectedRow = workRequestJTable1.getSelectedRow();
    if (selectedRow < 0) {
        JOptionPane.showMessageDialog(this, "Please select a row.", "Warning", JOptionPane.WARNING_MESSAGE);
        return;
    }

    //DefaultTableModel model = (DefaultTableModel) workRequestJTable1.getModel();
    Object[] row = workRequestQueue.get(selectedRow);

    String status = (String) row[3]; // 获取状态列
    
    System.out.println("Selected status: '" + status + "'");
    if (!"Approve".equalsIgnoreCase(status.trim())) {
        JOptionPane.showMessageDialog(this, "Only Approved requests can be added.", "Warning", JOptionPane.WARNING_MESSAGE);
        return;
    }

    String eventName = (String) row[0];
    String category = (String) row[7];
    String actualPrice = (String) row[6];

    // 从 EventManagementJPanel 中查找匹配的条目
    Event matchingEvent = null;
    for (Event e : EventManagementJPanel.eventList) {
        if (eventName.equals(e.getEventName())) {
            matchingEvent = e;
            break;
        }
    }

    if (matchingEvent == null) {
        JOptionPane.showMessageDialog(this, "Matching event not found in Event Management.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // 创建新行数据
    Object[] newRow = new Object[]{
        eventName,
        matchingEvent.getEventDate(),
        matchingEvent.getEventTime(),
        matchingEvent.getVenue(),
        actualPrice,
        "" // Sales 可留空或设置初始值
    };
    
    System.out.println("Adding row to TicketInformation: " + java.util.Arrays.toString(newRow));

   try {
    // 确保 TicketInformation 已正确添加到 userProcessContainer
    TicketInformation ticketInfoPanel = null;
    for (Component comp : userProcessContainer.getComponents()) {
        if (comp instanceof TicketInformation) {
            ticketInfoPanel = (TicketInformation) comp;
            break;
        }
    }

    if (ticketInfoPanel == null) {
        JOptionPane.showMessageDialog(this, "Ticket Information panel not found.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // 调用 addEventToCategory 方法
    ticketInfoPanel.addEventToCategory(category, newRow);
    JOptionPane.showMessageDialog(this, "Event added to Ticket Information.", "Success", JOptionPane.INFORMATION_MESSAGE);
} catch (Exception e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, "Error updating Ticket Information panel.", "Error", JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_btnAddtoListActionPerformed
    private void populateTable() {
            DefaultTableModel model = (DefaultTableModel) workRequestJTable1.getModel();
            model.setRowCount(0);
            
         for (Object[] row : workRequestQueue) {
             System.out.println("Populating row: " + java.util.Arrays.toString(row)); // 调试输出
            // 显示该用户相关的请求
            if (row[2] == null || row[2].equals(userAccount.getUsername())) {
                model.addRow(row);
            }
        }
    }
    
    public void refreshTable() {
    populateTable(); 
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignJButton1;
    private javax.swing.JButton btnAddtoList;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton processJButton1;
    private javax.swing.JButton refreshJButton1;
    private javax.swing.JTable workRequestJTable1;
    // End of variables declaration//GEN-END:variables
}
