/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Organizer;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.OrganizerEnterprise;
import Business.Organization.Organization;
import Business.Role.OrganizerRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import Business.Organization.ConcertPlanningOrganization;

/**
 *
 * @author zhangdi
 */
public class OrganizerWorkAreaJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private OrganizerEnterprise enterprise;
    private UserAccount userAccount;
    private ConcertPlanningOrganization organization;
    private OrganizerRole organizerRole;
    
    /**
     * Creates new form OrganizerWorkAreaJPanel
     */

    public OrganizerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, ConcertPlanningOrganization org, OrganizerEnterprise enterprise, EcoSystem business) {
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.organization = org;
        this.userAccount = account;
        
        initComponents();
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnEventMgt = new javax.swing.JButton();
        btnRevenueSum = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel1.setText("Organizer Work Area");

        btnEventMgt.setText("Event Management");
        btnEventMgt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEventMgtActionPerformed(evt);
            }
        });

        btnRevenueSum.setText("Revenue Summary");
        btnRevenueSum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRevenueSumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRevenueSum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEventMgt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(407, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel1)
                .addGap(60, 60, 60)
                .addComponent(btnEventMgt)
                .addGap(32, 32, 32)
                .addComponent(btnRevenueSum)
                .addContainerGap(220, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEventMgtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEventMgtActionPerformed
        // TODO add your handling code here:
        EventManagementJPanel emjp = new EventManagementJPanel(userProcessContainer, userAccount, enterprise, organization);
        userProcessContainer.add("EventManagementJPanel", emjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    
    }//GEN-LAST:event_btnEventMgtActionPerformed

    private void btnRevenueSumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRevenueSumActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnRevenueSumActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEventMgt;
    private javax.swing.JButton btnRevenueSum;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables


}
