/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Organizer;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import Business.Enterprise.Enterprise;
import Business.Enterprise.OrganizerEnterprise;
import Model.Event;
import Business.Organization.ConcertPlanningOrganization;
import Business.Organization.Organization;
import Business.Organization.VenueOperationsOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.VenueWorkRequest;
import Business.WorkQueue.WorkRequest;
import ui.Venue.VenueManagementJPanel;


/**
 *
 * @author zhangdi
 */
public class RequestVenueJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise; // 企业上下文
    private UserAccount userAccount; // 当前用户
    private Organization organization; // 演唱会组织机构
    private Event selectedEvent; // 选中的事件    
   

    /**
     * Creates new form RequestVenueJPanel
     */
    public RequestVenueJPanel(JPanel userProcessContainer, UserAccount userAccount, Enterprise enterprise, Event selectedEvent) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.selectedEvent = selectedEvent;
        //this.organization=organization;
        this.enterprise = enterprise;
        
 
        populateEventDetails(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtEventName = new javax.swing.JTextField();
        txtEventDate = new javax.swing.JTextField();
        txtEventTime = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMaxCapacity = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnSendRequest = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSpecialRequest = new javax.swing.JTextArea();
        btnBack = new javax.swing.JButton();
        txtVenue = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jLabel1.setText("Request a Venue");

        jLabel2.setText("Event Name:");

        jLabel3.setText("Event Date:");

        jLabel4.setText("Event Time:");

        btnSendRequest.setText("Send Request");
        btnSendRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendRequestActionPerformed(evt);
            }
        });

        jLabel5.setText("Special Request:");

        jLabel7.setText("Maximum Capacity:");

        jLabel8.setText("Venue:");

        txtSpecialRequest.setColumns(20);
        txtSpecialRequest.setRows(5);
        jScrollPane1.setViewportView(txtSpecialRequest);

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSendRequest)
                .addGap(291, 291, 291))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(251, 251, 251))
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtEventDate, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEventName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEventTime, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaxCapacity, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtVenue, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnBack))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtEventName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtEventDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtEventTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtMaxCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtVenue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(32, 32, 32)
                .addComponent(btnSendRequest)
                .addContainerGap(62, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendRequestActionPerformed
        // TODO add your handling code here:
        String venue = txtVenue.getText().trim();
        String maxCapacityStr = txtMaxCapacity.getText().trim();
        if (venue.isEmpty() || maxCapacityStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Venue and Maximum Capacity are required.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int maxCapacity;
        try {
            maxCapacity = Integer.parseInt(maxCapacityStr);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Maximum Capacity must be a number.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Object[] workRequest = new Object[6];
        workRequest[0] = txtEventName.getText(); // Performance Name
        workRequest[1] = txtEventDate.getText();   // Sender
        workRequest[2] = txtEventTime.getText();       // Receiver
        workRequest[3] = maxCapacity;                   // Status
        workRequest[4] = venue;                          // Remark
        workRequest[5] = txtSpecialRequest.getText(); // Suggested Price

        // 这里需要调用 TicketingAgent 的 UI 刷新方法，模拟将 WorkRequest 发送到对方的队列
        VenueManagementJPanel.addWorkRequest(workRequest);
        JOptionPane.showMessageDialog(this, "Request sent!", "Success", JOptionPane.INFORMATION_MESSAGE);

        txtEventName.setText("");
        txtEventDate.setText("");
        txtEventTime.setText("");
        txtMaxCapacity.setText("");
        txtVenue.setText("");
        txtSpecialRequest.setText("");
    }//GEN-LAST:event_btnSendRequestActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed
 private void populateEventDetails() {
        // 填充选中事件的信息
        txtEventName.setText(selectedEvent.getEventName()); // 填充事件名称
        txtEventDate.setText(selectedEvent.getEventDate()); // 填充事件日期
        txtEventTime.setText(selectedEvent.getEventTime()); // 填充事件时间
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSendRequest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtEventDate;
    private javax.swing.JTextField txtEventName;
    private javax.swing.JTextField txtEventTime;
    private javax.swing.JTextField txtMaxCapacity;
    private javax.swing.JTextArea txtSpecialRequest;
    private javax.swing.JTextField txtVenue;
    // End of variables declaration//GEN-END:variables
}
